### ISSUE TITLE
Style '.tgrid-mobile-container .selected' should not has '!important' flag

### ISSUE THREAD

**Issue by feafarot** [TesserisPro/tgrid#17]
``` css
.tgrid-mobile-container .selected {
    background-color: #dbdbde !important;
}
```
